### ISSUE TITLE
GPIO numbers and images

### ISSUE THREAD

**Issue by Arold** [jadonk/bone101#12]
If I'm not mistaken, several GPIO numbers are wrong in images:

**cape-headers.png**
GPIO_122 shoud be GPIO_112
![image](https://cloud.githubusercontent.com/assets/8535282/5534610/fa8c826c-8a32-11e4-800c-c3fdeada401b.png)

**cape-headers-digital.png**
GPIO_123 shoud be GPIO_113
GPIO_121 shoud be GPIO_111
GPIO_122 shoud be GPIO_112
GPIO_120 shoud be GPIO_110
![image](https://cloud.githubusercontent.com/assets/8535282/5534608/f2a94698-8a32-11e4-80ce-e77b6a75720a.png)

**cape-headers-pwm.png**
GPIO_122 shoud be GPIO_112
![image](https://cloud.githubusercontent.com/assets/8535282/5534605/e9703118-8a32-11e4-9031-0173a1040944.png)

**cape-headers-analog.png**
GPIO_123 shoud be GPIO_113
GPIO_121 shoud be GPIO_111
GPIO_122 shoud be GPIO_112
GPIO_120 shoud be GPIO_110
![image](https://cloud.githubusercontent.com/assets/8535282/5534601/cef31c7e-8a32-11e4-9d99-7fce01cf018a.png)

**cape-headers-serial.png**
GPIO_123 shoud be GPIO_113
GPIO_121 shoud be GPIO_111
GPIO_122 shoud be GPIO_112
GPIO_120 shoud be GPIO_110
![image](https://cloud.githubusercontent.com/assets/8535282/5534599/c062c894-8a32-11e4-87a5-865369fb2037.png)

**cape-headers-i2c.png**
GPIO_123 shoud be GPIO_113
GPIO_121 shoud be GPIO_111
GPIO_122 shoud be GPIO_112
GPIO_120 shoud be GPIO_110
![image](https://cloud.githubusercontent.com/assets/8535282/5534597/b4f8963c-8a32-11e4-8798-a8061411253b.png)

**black-emmc-and-hdmi-pins.png**
GPIO_122 shoud be GPIO_112
![image](https://cloud.githubusercontent.com/assets/8535282/5534595/a47f6f6a-8a32-11e4-8c55-81322a2a3cf0.png)

Best regards.

**Comment by jadonk** [comment]
I believe this is fixed now.

**Comment by jadonk** [comment]
Maybe it wasn't fixed until a06e631f7dfdee3c030d32cdc15747b050cf6d27
